eureka:
  client:
    service-url:
#      eureka服务端开启验证之后注入 需要用户名和密码
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: provider
