eureka:
  client:
    #单机环境，不从eureka上拉取信息
    fetch-registry: false
    #单机，不注册进入eureka
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    #eureka服务主机名称
    hostname: localhost
#    关闭自我保护机制
  server:
    enable-self-preservation: false
server:
  port: 8000
spring:
  application:
    name: eureka-service
#  security:
#    user:
#      name: root
#      password: root