eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: eureka-provider:8082
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: eureka-provider
