eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: eureka-consumer:8004
    prefer-ip-address: true
server:
  port: 8004
spring:
  application:
    name: eureka-consumer
