eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    instance-id: eureka-provider-hystrix:8084
    prefer-ip-address: true
server:
  port: 8084
spring:
  application:
    name: eureka-hystrix
